mytestkey=This value is from LOCAL properties file

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.initialization-mode=always


stripe.provider.create.payment.url=http://localhost:8083/v1/payments


management.endpoints.web.exposure.include=*
management.endpoint.health.enabled=true
management.health.circuitbreakers.enabled=true
 
management.endpoint.health.show-details=always 

# Resilience4j Circuit Breaker configurations
resilience4j.circuitbreaker.instances.payment-processing-service.failureRateThreshold=40
resilience4j.circuitbreaker.instances.payment-processing-service.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.payment-processing-service.waitDurationInOpenState=300s
resilience4j.circuitbreaker.instances.payment-processing-service.register-health-indicator=true
resilience4j.circuitbreaker.instances.payment-processing-service.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.payment-processing-service.permittedNumberOfCallsInHalfOpenState=2
 
resilience4j.circuitbreaker.instances.payment-processing-service.slidingWindowSize=10
resilience4j.circuitbreaker.instances.payment-processing-service.slidingWindowType=COUNT_BASED


stripe.endpointSecret=whsec_8c76eefe41eaf53f9e87b62a5aa0b6c1408d421ad24a91782bc4571412d5f167



#logging.level.root=INFO
#logging.level.com.hulkhiretech=DEBUG

management.tracing.enabled=true
management.tracing.sampling.probability=1.0
